### ISSUE TITLE
Kong redirects to a blank page when a protected URL is request

### ISSUE THREAD

**Issue by abrahamy** [eHealthAfrica/gateway-manager#5]
I am getting what seems to be an error with the `gateway-manager` when a protected URL is requested. Kong redirects to the keycloak login page as required but the page is blank. However, when I visit `/keycloak/auth` directly I can login with the master realm credentials.

I strongly suspect that this is an issue with the hard coding of the login theme on this line: https://github.com/eHealthAfrica/gateway-manager/blob/257c1a34b88a6545d33e31b3ad0c1824c00cc491/gateway-manager/src/manage_realm.py#L76.

Could we extend the `add_realm` entry point of the container to optionally take the login theme as a parameter and default to using keycloak's default login theme when the parameter is not provided?

@shawnsarwar

**Comment by shawnsarwar** [comment]
Good idea. Please go ahead and make a PR and tag @obdulia-losantos as I'm out of town starting this evening.

**Comment by shawnsarwar** [comment]
@abrahamy The script should check to see if the `LOGIN_THEME` environment variable is set, and if so, try to use the value. If it's not set, then it should not try to set a theme.
